version: '3.7'

networks:
  bridge:
    external: true
    name: ${NETWORKS}

services:
  office:
    image: nginx:alpine
    container_name: ${CONTAINER_ONE_NAME}
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.office.entrypoints=${ENTRYPOINTS}"
      - "traefik.http.routers.office.tls.certresolver=lets-encr"
      - "traefik.http.routers.office.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.office.tls.options=default"
      - "traefik.http.routers.office.middlewares=secure-headers@file"

  admin:
    image: nginx:alpine
    container_name: ${CONTAINER_TWO_NAME}
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist/:/usr/share/nginx/html/admin/
    networks:
      - bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=${ENTRYPOINTS}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=lets-encr"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.options=default"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=secure-headers@file,traefik-compress@file"
        #      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=ipwhitelist@file" # 禁止對外連接