version: '3.7'

networks:
  bridge:
    external:
      name: ${NETWORKS}

services:
  office:
    image: nginx:alpine
    container_name: 0verOffice
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.office.entrypoints=websecure"
      - "traefik.http.routers.office.tls.certresolver=lets-encr"
      - "traefik.http.routers.office.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.office.tls.options=default"
      - "traefik.http.routers.office.middlewares=secure-headers@file"

  admin:
    image: nginx:alpine
    container_name: 0verAdmin
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist/:/usr/share/nginx/html/admin/
    networks:
      - bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=lets-encr"
      - "traefik.http.routers.admin.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.admin.tls.options=default"
      - "traefik.http.routers.admin.middlewares=secure-headers@file"